jira:
  image: dnhsoft/jira:6.4.1
  links:
   - db
  ports:
   - "8080:8080"
  volumes:
   - ".data:/var/atlassian/application-data/jira/data"

db:
  image: tutum/mysql:5.6
  volumes:
   - ".db:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456

pma:
  image: dnhsoft/phpmyadmin:4.3
  links:
   - db
  ports:
   - "8100:80"

